### ISSUE TITLE
push comment along with worklog entry

### ISSUE THREAD

**Issue by daroczig** [kraiz/hamster-bridge#11]
I really enjoy this plugin, and an IMHO useful  feature came to my mind. Currently, `master-bridge` logs the time to the related ticket without any details, but the `add_worklog` from [jira](http://pythonhosted.org/jira/) also has the option to push some comments for the saved worklog.

Not sure how much work would it require (it seems to me that it might be as easy as passing the hamster `description` as `comment`), but it would be nice to save the comments from Hamster into JIRA as well. E.g. I use `hamster` by specifying the JIRA ticket reference, then providing some details as comments, sometimes maybe also adding tags -- but that's not important at all.

Current behavior: when I type `JIRA-1,doing foo an bar` in hamster, then the logged time is saved to `JIRA-1` ticket without any details.
Suggested behavior: when I type `JIRA-1,doing foo an bar` in hamster, then the logged time is saved to `JIRA-1` ticket with the `doing foo and bar` as the comment.

**Comment by kraiz** [comment]
Saw the "comment" parameter in the new jira-library (from #10), too. I also missed this possible feature when hacking together the initial bridge version. I'm with you, we need this!

I think i prefer the mapping of the task description to the jira comment over the separator approach because of 2 reasons:
1) Hamster has this autocomplete which helps you resuming a task. So you end up with many time slots spend for the same task. The statistics feature with the fancy charts works great this way and helps me to keep an overview of how much time i actually spent on a task/ticket. And the one-to-one-relation from hamster task to jira ticket whould be cut off when you change the title as you do different things on a task.
2) A more personal workflow problem for me is, that i start the task before actually reading the ticket description and really don't know what i actually do in this "task". I would add/fill the description field the hamster as i'm doing it or before stopping.

What do you think?

**Comment by daroczig** [comment]
Sounds great! It would be an extremely useful feature.

And I think I tried to describe the same thing, I mean when I write `JIRA-1,doing foo and bar` in the Gnome3 `hamster` extension, then `JIRA-1` is saved as the task `title` and `doing foo and bar` as the description.

Looking forward to version `0.5.0` :) Let me know if I can help testing/debugging something.

**Comment by kraiz** [comment]
Hey, there's a new version waiting to beta test. The necessary change was indeed very ...jimp :)

**Comment by daroczig** [comment]
Wow, this works :+1: Thanks a lot!

**Comment by kraiz** [comment]
Tested this "in production" (@work) successfully, too :)

**Comment by daroczig** [comment]
I've been using the updated version of `hasmter-bridge` for two workdays, and it does the job without any issues. This small change added a lot of extra value for me :) Thanks again.
